# Generated by Django 5.2.14 on 2026-05-23 11:35

import common.media_storage
from django.db import migrations, models


def backfill_media_provider(apps, schema_editor):
    Invoice = apps.get_model("payments", "Invoice")
    Invoice.objects.filter(media_provider="AUTO").exclude(pdf_file__isnull=True).exclude(
        pdf_file=""
    ).update(media_provider="LOCAL")


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_invoice_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="media_provider",
            field=models.CharField(
                choices=[
                    ("AUTO", "Auto (use Platform Config)"),
                    ("LOCAL", "Local"),
                    ("CLOUDINARY", "Cloudinary"),
                    ("S3", "AWS S3"),
                ],
                db_index=True,
                default="AUTO",
                help_text="Where this invoice PDF is stored.",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_media_provider, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="invoice",
            name="pdf_file",
            field=common.media_storage.ProviderAwareFileField(
                blank=True, null=True, upload_to="payments/invoices/"
            ),
        ),
    ]
