# Generated by Django 5.2.14 on 2026-05-22 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employerverificationaccess',
            name='verification_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_accesses', to='verification.verificationrecord'),
        ),
        migrations.AddField(
            model_name='employerverificationreport',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employerverificationreport',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='employers.employer'),
        ),
        migrations.AddField(
            model_name='employerverificationreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_verification_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
