# Generated by Django 5.2.14 on 2026-05-22 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_initial'),
        ('verification', '0002_verificationcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['status', 'is_active'], name='employers_e_status_a93b57_idx'),
        ),
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['status', 'is_verified'], name='employers_e_status_213df3_idx'),
        ),
        migrations.AddIndex(
            model_name='employer',
            index=models.Index(fields=['country', 'status'], name='employers_e_country_3a6353_idx'),
        ),
        migrations.AddIndex(
            model_name='employeruser',
            index=models.Index(fields=['employer', 'role'], name='employers_e_employe_09dce8_idx'),
        ),
        migrations.AddIndex(
            model_name='employeruser',
            index=models.Index(fields=['employer', 'is_active'], name='employers_e_employe_9b72c3_idx'),
        ),
        migrations.AddIndex(
            model_name='employerverificationaccess',
            index=models.Index(fields=['employer', 'status'], name='employers_e_employe_8d22a2_idx'),
        ),
        migrations.AddIndex(
            model_name='employerverificationaccess',
            index=models.Index(fields=['candidate', 'status'], name='employers_e_candida_eb2065_idx'),
        ),
        migrations.AddIndex(
            model_name='employerverificationaccess',
            index=models.Index(fields=['verification_record', 'status'], name='employers_e_verific_b79241_idx'),
        ),
        migrations.AddIndex(
            model_name='employerverificationaccess',
            index=models.Index(fields=['expires_at'], name='employers_e_expires_709b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='employerverificationreport',
            index=models.Index(fields=['employer', 'generated_at'], name='employers_e_employe_ee78f3_idx'),
        ),
        migrations.AddIndex(
            model_name='employerverificationreport',
            index=models.Index(fields=['candidate', 'generated_at'], name='employers_e_candida_024bbb_idx'),
        ),
        migrations.AddIndex(
            model_name='employerverificationreport',
            index=models.Index(fields=['expires_at'], name='employers_e_expires_6c6180_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeruser',
            constraint=models.UniqueConstraint(fields=('employer', 'user'), name='unique_employer_user_membership'),
        ),
        migrations.AddConstraint(
            model_name='employerverificationaccess',
            constraint=models.UniqueConstraint(fields=('employer', 'candidate', 'verification_record'), name='unique_employer_candidate_verification_access'),
        ),
    ]
