# Generated by Django 5.2.14 on 2026-05-23 11:35

import common.media_storage
from django.db import migrations, models


def backfill_media_provider(apps, schema_editor):
    Employer = apps.get_model("employers", "Employer")
    EmployerVerificationReport = apps.get_model("employers", "EmployerVerificationReport")

    Employer.objects.filter(media_provider="AUTO").exclude(logo__isnull=True).exclude(
        logo=""
    ).update(media_provider="LOCAL")

    EmployerVerificationReport.objects.filter(media_provider="AUTO").exclude(
        report_file__isnull=True
    ).exclude(report_file="").update(media_provider="LOCAL")


class Migration(migrations.Migration):

    dependencies = [
        ("employers", "0003_employer_employers_e_status_a93b57_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="media_provider",
            field=models.CharField(
                choices=[
                    ("AUTO", "Auto (use Platform Config)"),
                    ("LOCAL", "Local"),
                    ("CLOUDINARY", "Cloudinary"),
                    ("S3", "AWS S3"),
                ],
                db_index=True,
                default="AUTO",
                help_text="Where this employer's media (e.g., logo) is stored.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employerverificationreport",
            name="media_provider",
            field=models.CharField(
                choices=[
                    ("AUTO", "Auto (use Platform Config)"),
                    ("LOCAL", "Local"),
                    ("CLOUDINARY", "Cloudinary"),
                    ("S3", "AWS S3"),
                ],
                db_index=True,
                default="AUTO",
                help_text="Where this report file is stored.",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_media_provider, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="employer",
            name="logo",
            field=common.media_storage.ProviderAwareImageField(
                blank=True, null=True, upload_to="employers/logos/"
            ),
        ),
        migrations.AlterField(
            model_name="employerverificationreport",
            name="report_file",
            field=common.media_storage.ProviderAwareFileField(
                blank=True, null=True, upload_to="verification/reports/"
            ),
        ),
    ]
