# Generated by Django 5.2.14 on 2026-05-22 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('verification_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('credential_type', models.CharField(choices=[('DEGREE', 'Degree'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate'), ('TRANSCRIPT', 'Transcript'), ('LICENSE', 'License'), ('EMPLOYMENT', 'Employment'), ('OTHER', 'Other')], max_length=30)),
                ('credential_name', models.CharField(max_length=255)),
                ('credential_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('MATCHED', 'Matched'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='PENDING', max_length=30)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_created_by', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='institutions.institution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Record',
                'verbose_name_plural': 'Verification Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('STATUS_CHANGED', 'Status Changed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked'), ('COMMENTED', 'Commented')], max_length=30)),
                ('previous_status', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(blank=True, max_length=30, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verification_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='verification.verificationrecord')),
            ],
            options={
                'verbose_name': 'Verification Event',
                'verbose_name_plural': 'Verification Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CredentialDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('ORIGINAL', 'Original'), ('TRANSCRIPT', 'Transcript'), ('SUPPORTING', 'Supporting'), ('IDENTITY', 'Identity')], default='ORIGINAL', max_length=30)),
                ('file', models.FileField(upload_to='verification/documents/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verification_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='verification.verificationrecord')),
            ],
            options={
                'verbose_name': 'Credential Document',
                'verbose_name_plural': 'Credential Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('request_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('employer_notes', models.TextField(blank=True, null=True)),
                ('candidate_response_notes', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='employers.employer')),
                ('verification_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='verification.verificationrecord')),
            ],
            options={
                'verbose_name': 'Verification Request',
                'verbose_name_plural': 'Verification Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
