# Generated by Django 5.2.14 on 2026-05-22 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal comments visible only to staff/admins')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_comments', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='verification.verificationcomment')),
                ('verification_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='verification.verificationrecord')),
            ],
            options={
                'verbose_name': 'Verification Comment',
                'verbose_name_plural': 'Verification Comments',
                'ordering': ['created_at'],
            },
        ),
    ]
