# Generated by Django 5.2.14 on 2026-05-22 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_employer_employers_e_status_a93b57_idx_and_more'),
        ('institutions', '0003_institutionrequest_and_more'),
        ('verification', '0002_verificationcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_documents_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verificationevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verificationrecord',
            name='credential_reference',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrecord',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrecord',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='verificationrecord',
            name='verified_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='credentialdocument',
            index=models.Index(fields=['verification_record', 'document_type'], name='verificatio_verific_3eccc1_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationevent',
            index=models.Index(fields=['verification_record', 'created_at'], name='verificatio_verific_6db7f4_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationevent',
            index=models.Index(fields=['event_type', 'created_at'], name='verificatio_event_t_edd358_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrecord',
            index=models.Index(fields=['candidate', 'status'], name='verificatio_candida_56e02a_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrecord',
            index=models.Index(fields=['institution', 'status'], name='verificatio_institu_8573bf_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrecord',
            index=models.Index(fields=['status', 'submitted_at'], name='verificatio_status_9a96de_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['employer', 'status'], name='verificatio_employe_186472_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['candidate', 'status'], name='verificatio_candida_0bbf7a_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['verification_record', 'status'], name='verificatio_verific_a91346_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['expires_at'], name='verificatio_expires_192f18_idx'),
        ),
        migrations.AddConstraint(
            model_name='verificationrequest',
            constraint=models.UniqueConstraint(fields=('employer', 'candidate', 'verification_record'), name='unique_verification_request_per_employer_candidate_record'),
        ),
    ]
