# Generated by Django 5.2.14 on 2026-05-23 11:35

import common.media_storage
from django.db import migrations, models


def backfill_media_provider(apps, schema_editor):
    CredentialDocument = apps.get_model("verification", "CredentialDocument")
    CredentialDocument.objects.filter(media_provider="AUTO").exclude(file="").update(
        media_provider="LOCAL"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0003_alter_credentialdocument_uploaded_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="credentialdocument",
            name="media_provider",
            field=models.CharField(
                choices=[
                    ("AUTO", "Auto (use Platform Config)"),
                    ("LOCAL", "Local"),
                    ("CLOUDINARY", "Cloudinary"),
                    ("S3", "AWS S3"),
                ],
                db_index=True,
                default="AUTO",
                help_text="Where this credential document file is stored.",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_media_provider, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="credentialdocument",
            name="file",
            field=common.media_storage.ProviderAwareFileField(
                upload_to="verification/documents/"
            ),
        ),
    ]
