# Generated by Django 5.2.14 on 2026-05-23 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformConfig",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "default_upload_provider",
                    models.CharField(
                        choices=[
                            ("AUTO", "Auto (use Platform Config)"),
                            ("LOCAL", "Local"),
                            ("CLOUDINARY", "Cloudinary"),
                            ("S3", "AWS S3"),
                        ],
                        db_index=True,
                        default="LOCAL",
                        max_length=20,
                    ),
                ),
                ("enable_local", models.BooleanField(default=True)),
                ("enable_cloudinary", models.BooleanField(default=True)),
                ("enable_s3", models.BooleanField(default=True)),
                ("smtp_host", models.CharField(blank=True, max_length=255, null=True)),
                ("smtp_port", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "smtp_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "smtp_from_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("smtp_use_tls", models.BooleanField(default=True)),
                ("smtp_use_ssl", models.BooleanField(default=False)),
                (
                    "cloudinary_folder",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("aws_region", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "aws_bucket_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platform_configs_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Config",
                "verbose_name_plural": "Platform Config",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["default_upload_provider"],
                        name="common_plat_default_2387a4_idx",
                    )
                ],
            },
        ),
    ]
