# Generated by Django 5.2.14 on 2026-05-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_institution_user_is_mfa_enabled_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('institutions', '0003_institutionrequest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'institution'], name='accounts_us_role_c37ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_email_verified', 'is_mfa_enabled'], name='accounts_us_is_emai_8c6b1b_idx'),
        ),
    ]
