"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
    TESTING=(bool, False),
    DJANGO_ENV=(str, "local"),
)

env_file = BASE_DIR / ".env"
if env_file.exists():
    environ.Env.read_env(env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-1h0s4z)7g$vy=nvpitxwg!$12l5ogtr0*5bforlq-+hp$(k8hw",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=env("DJANGO_ENV") == "local")

ALLOWED_HOSTS = env.list(
    "ALLOWED_HOSTS",
    default=["localhost", "127.0.0.1"],
)


# Application definition

INSTALLED_APPS = [

    # ==========================================
    # UNFOLD ADMIN
    # ==========================================
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",

    # ==========================================
    # DJANGO CORE
    # ==========================================
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # ==========================================
    # THIRD PARTY APPS
    # ==========================================
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "django_filters",
    "guardian",
    "django_celery_results",
    "django_celery_beat",
    "channels",
    "drf_spectacular",
    "storages",
    "allauth",
    "allauth.account",

    # ==========================================
    # LOCAL APPS
    # ==========================================
    "accounts",
    "institutions",
    "verification",
    "wallets",
    "audit",
    "employers",
    "payments",
    "common",
]

AUTH_USER_MODEL = "accounts.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",

    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",

    # ALLAUTH
    "allauth.account.middleware.AccountMiddleware",

    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": env.db(
        "DATABASE_URL",
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    )
}

if env.bool("TESTING", default=False) or "test" in os.sys.argv:
    DATABASES["default"]["NAME"] = env(
        "TEST_DATABASE_NAME",
        default=":memory:",
    )

DATABASES["default"].setdefault("CONN_MAX_AGE", env.int("DB_CONN_MAX_AGE", default=0))


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
)

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_ID = 1

ACCOUNT_LOGIN_METHODS = {"email"}

ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

ACCOUNT_UNIQUE_EMAIL = True

ACCOUNT_EMAIL_VERIFICATION = "optional"

LOGIN_REDIRECT_URL = "/admin/"
LOGOUT_REDIRECT_URL = "/admin/login/"

def environment_callback(request):

    if request.user.is_superuser:
        return ["Super Admin", "danger"]

    return ["Certrium", "info"]


UNFOLD = {

    # =========================================================
    # BRANDING
    # =========================================================

    "SITE_TITLE": "Certrium Admin",
    "SITE_HEADER": "Certrium",
    "SITE_SUBHEADER": "Trust Verification Infrastructure",
    # "SITE_ICON": lambda request: static("formula/images/logo.svg"),
    # "SITE_LOGO": {
    #     "light": lambda request: static("images/logo.svg"),
    #     "dark": lambda request: static("images/logo.svg"),
    # },

    "SITE_ICON": {
        "light": lambda request: static("images/logo-light.png"),  # light mode
        "dark": lambda request: static("images/logo-dark.png"),  # dark mode
    },

    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "sizes": "32x32",
            "type": "image/svg+xml",
            "href": lambda request: static("favicon.svg"),
        }
    ],

    # =========================================================
    # UI SETTINGS
    # =========================================================

    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SHOW_BACK_BUTTON": True,
    "SHOW_UI_WARNINGS": False,

    "ENVIRONMENT": "config.settings.environment_callback",

    "THEME": None,

    "BORDER_RADIUS": "10px",

    # =========================================================
    # LOGIN
    # =========================================================

    "LOGIN": {
        "image": lambda request: static("branding/login-bg.jpg"),
        "redirect_after": lambda request: reverse_lazy("admin:index"),
    },

    # =========================================================
    # CUSTOM STYLES
    # =========================================================

    "STYLES": [
        lambda request: static("css/admin.css"),
    ],

    "SCRIPTS": [
        lambda request: static("js/admin.js"),
    ],

    # =========================================================
    # COLORS
    # =========================================================

    "COLORS": {

        "primary": {

            "50": "255 241 242",
            "100": "255 228 230",
            "200": "254 205 211",
            "300": "253 164 175",
            "400": "251 113 133",
            "500": "244 63 94",
            "600": "225 29 72",
            "700": "190 24 74",
            "800": "159 18 57",
            "900": "136 19 55",
            "950": "76 5 25",
        },

        "base": {

            "50": "249 250 251",
            "100": "243 244 246",
            "200": "229 231 235",
            "300": "209 213 219",
            "400": "156 163 175",
            "500": "75 85 99",
            "600": "55 65 81",
            "700": "43 43 43",
            "800": "31 31 31",
            "900": "24 24 24",
            "950": "14 14 14"

        },
    },

    # =========================================================
    # SIDEBAR
    # =========================================================

    "SIDEBAR": {

        "show_search": True,
        "show_all_applications": False,
        "command_search": True,
        "show_app_list": True,
        

        "navigation": [

            # =================================================
            # DASHBOARD
            # =================================================

            {
                "title": _("Dashboard"),
                "separator": True,
                "collapsible": False,

                "items": [
                    {
                        "title": _("Overview"),
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },

            # =================================================
            # USER MANAGEMENT
            # =================================================

            {
                "title": _("User Management"),
                "separator": True,
                "collapsible": True,

                "items": [

                    {
                        "title": _("Users"),
                        "icon": "group",
                        "link": reverse_lazy(
                            "admin:accounts_user_changelist"
                        ),
                    },

                    {
                        "title": _("Institutions"),
                        "icon": "school",
                        "link": reverse_lazy(
                            "admin:institutions_institution_changelist"
                        ),
                    },

                    {
                        "title": _("Institution Requests"),
                        "icon": "domain_add",
                        "link": reverse_lazy(
                            "admin:institutions_institutionrequest_changelist"
                        ),
                    },

                    {
                        "title": _("Employers"),
                        "icon": "business",
                        "link": reverse_lazy(
                            "admin:employers_employer_changelist"
                        ),
                    },
                ],
            },

            # =================================================
            # VERIFICATION
            # =================================================

            {
                "title": _("Verification"),
                "separator": True,
                "collapsible": True,

                "items": [

                    {
                        "title": _("Verification Records"),
                        "icon": "verified",
                        "link": reverse_lazy(
                            "admin:verification_verificationrecord_changelist"
                        ),
                    },

                    {
                        "title": _("Credential Documents"),
                        "icon": "description",
                        "link": reverse_lazy(
                            "admin:verification_credentialdocument_changelist"
                        ),
                    },

                    {
                        "title": _("Verification Events"),
                        "icon": "history",
                        "link": reverse_lazy(
                            "admin:verification_verificationevent_changelist"
                        ),
                    },
                ],
            },

            # =================================================
            # DIGITAL WALLETS
            # =================================================

            {
                "title": _("Wallets"),
                "separator": True,
                "collapsible": True,

                "items": [

                    {
                        "title": _("Wallets"),
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy(
                            "admin:wallets_wallet_changelist"
                        ),
                    },

                    {
                        "title": _("Wallet Records"),
                        "icon": "badge",
                        "link": reverse_lazy(
                            "admin:wallets_walletrecord_changelist"
                        ),
                    },

                    {
                        "title": _("Wallet Shares"),
                        "icon": "share",
                        "link": reverse_lazy(
                            "admin:wallets_walletshare_changelist"
                        ),
                    },
                ],
            },

            # =================================================
            # PAYMENTS
            # =================================================

            {
                "title": _("Payments"),
                "separator": True,
                "collapsible": True,

                "items": [

                    {
                        "title": _("Transactions"),
                        "icon": "payments",
                        "link": reverse_lazy(
                            "admin:payments_paymenttransaction_changelist"
                        ),
                    },

                    {
                        "title": _("Invoices"),
                        "icon": "receipt_long",
                        "link": reverse_lazy(
                            "admin:payments_invoice_changelist"
                        ),
                    },

                    {
                        "title": _("Subscriptions"),
                        "icon": "workspace_premium",
                        "link": reverse_lazy(
                            "admin:payments_usersubscription_changelist"
                        ),
                    },
                ],
            },

            # =================================================
            # AUDIT & SECURITY
            # =================================================

            {
                "title": _("Audit & Security"),
                "separator": True,
                "collapsible": True,

                "items": [

                    {
                        "title": _("Audit Logs"),
                        "icon": "policy",
                        "link": reverse_lazy(
                            "admin:audit_auditlog_changelist"
                        ),
                    },

                    {
                        "title": _("Security Events"),
                        "icon": "security",
                        "link": reverse_lazy(
                            "admin:audit_securityevent_changelist"
                        ),
                    },

                    {
                        "title": _("Activity Timeline"),
                        "icon": "timeline",
                        "link": reverse_lazy(
                            "admin:audit_activitytimeline_changelist"
                        ),
                    },
                ],
            },

            # =================================================
            # SYSTEM
            # =================================================

            {
                "title": _("System"),
                "separator": True,
                "collapsible": True,

                "items": [

                    {
                        "title": _("Groups"),
                        "icon": "admin_panel_settings",
                        "link": reverse_lazy(
                            "admin:auth_group_changelist"
                        ),
                    },

                    {
                        "title": _("Celery Tasks"),
                        "icon": "schedule",
                        "link": reverse_lazy(
                            "admin:django_celery_beat_periodictask_changelist"
                        ),
                    },
                ],
            },
        ],
    },
}

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"