# Generated by Django 5.2.14 on 2026-05-22 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitytimeline',
            index=models.Index(fields=['user', 'created_at'], name='audit_activ_user_id_17b1de_idx'),
        ),
        migrations.AddIndex(
            model_name='activitytimeline',
            index=models.Index(fields=['related_model', 'related_object_id'], name='audit_activ_related_6d6d0a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action_type', 'created_at'], name='audit_audit_action__eafc67_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='audit_audit_target__573821_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', 'event_type'], name='audit_secur_user_id_efa58c_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'created_at'], name='audit_secur_event_t_08e741_idx'),
        ),
    ]
