# Generated by Django 5.2.14 on 2026-05-22 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_alter_credentialdocument_uploaded_by_and_more'),
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='walletaccesslog',
            name='accessed_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='walletrecord',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('SHARED', 'Shared'), ('PUBLIC', 'Public')], db_index=True, default='PRIVATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='walletshare',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['owner', 'is_active'], name='wallets_wal_owner_i_906ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['owner', 'is_public'], name='wallets_wal_owner_i_fe4074_idx'),
        ),
        migrations.AddIndex(
            model_name='walletaccesslog',
            index=models.Index(fields=['wallet_share', 'accessed_at'], name='wallets_wal_wallet__21841f_idx'),
        ),
        migrations.AddIndex(
            model_name='walletaccesslog',
            index=models.Index(fields=['accessed_by_email', 'accessed_at'], name='wallets_wal_accesse_966e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='walletrecord',
            index=models.Index(fields=['wallet', 'visibility'], name='wallets_wal_wallet__db7102_idx'),
        ),
        migrations.AddIndex(
            model_name='walletrecord',
            index=models.Index(fields=['wallet', 'is_revoked'], name='wallets_wal_wallet__e1219c_idx'),
        ),
        migrations.AddIndex(
            model_name='walletrecord',
            index=models.Index(fields=['verification_record'], name='wallets_wal_verific_d14c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='walletshare',
            index=models.Index(fields=['wallet_record', 'status'], name='wallets_wal_wallet__145870_idx'),
        ),
        migrations.AddIndex(
            model_name='walletshare',
            index=models.Index(fields=['shared_with_email', 'status'], name='wallets_wal_shared__b39984_idx'),
        ),
        migrations.AddIndex(
            model_name='walletshare',
            index=models.Index(fields=['expires_at'], name='wallets_wal_expires_5b5be4_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletrecord',
            constraint=models.UniqueConstraint(fields=('wallet', 'verification_record'), name='unique_wallet_verification_record'),
        ),
    ]
