# Generated by Django 5.2.14 on 2026-05-22 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('document_type', models.CharField(choices=[('LICENSE', 'License'), ('ACCREDITATION', 'Accreditation'), ('GOVERNMENT_ID', 'Government ID'), ('TAX_DOCUMENT', 'Tax Document'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='institutions/documents/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='institutions.institution')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_institution_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institution Document',
                'verbose_name_plural': 'Institution Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstitutionStaff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('REVIEWER', 'Reviewer'), ('OPERATOR', 'Operator')], default='REVIEWER', max_length=30)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='institutions.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_staff_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institution Staff',
                'verbose_name_plural': 'Institution Staff',
                'ordering': ['-created_at'],
                'unique_together': {('institution', 'user')},
            },
        ),
    ]
