# Generated by Django 5.2.14 on 2026-05-22 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_institutiondocument_institutionstaff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWING', 'Reviewing'), ('CONTACTED', 'Contacted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Institution Request',
                'verbose_name_plural': 'Institution Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='institutiondomain',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['status', 'is_active'], name='institution_status_bcff6c_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['status', 'is_verified'], name='institution_status_254f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='institutioncontact',
            index=models.Index(fields=['institution', 'contact_type'], name='institution_institu_d6ed6d_idx'),
        ),
        migrations.AddIndex(
            model_name='institutioncontact',
            index=models.Index(fields=['institution', 'is_primary'], name='institution_institu_9bbf3c_idx'),
        ),
        migrations.AddIndex(
            model_name='institutioninvite',
            index=models.Index(fields=['institution', 'status'], name='institution_institu_93353b_idx'),
        ),
        migrations.AddIndex(
            model_name='institutioninvite',
            index=models.Index(fields=['email', 'status'], name='institution_email_8a2d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='institutioninvite',
            index=models.Index(fields=['expires_at'], name='institution_expires_a6caaa_idx'),
        ),
        migrations.AddConstraint(
            model_name='institutioncontact',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('institution',), name='unique_primary_contact_per_institution'),
        ),
        migrations.AddField(
            model_name='institutionrequest',
            name='converted_institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='institutions.institution'),
        ),
        migrations.AddField(
            model_name='institutionrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institutionrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_institution_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='institutionrequest',
            index=models.Index(fields=['status', 'created_at'], name='institution_status_e698d0_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionrequest',
            index=models.Index(fields=['institution_name'], name='institution_institu_47a6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='institutionrequest',
            index=models.Index(fields=['domain'], name='institution_domain_73bb6a_idx'),
        ),
    ]
