# Generated by Django 5.2.14 on 2026-05-23 11:35

import common.media_storage
from django.db import migrations, models


def backfill_media_provider(apps, schema_editor):
    Institution = apps.get_model("institutions", "Institution")
    InstitutionDocument = apps.get_model("institutions", "InstitutionDocument")

    Institution.objects.filter(media_provider="AUTO").exclude(logo__isnull=True).exclude(
        logo=""
    ).update(media_provider="LOCAL")

    InstitutionDocument.objects.filter(media_provider="AUTO").exclude(file="").update(
        media_provider="LOCAL"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0003_institutionrequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="media_provider",
            field=models.CharField(
                choices=[
                    ("AUTO", "Auto (use Platform Config)"),
                    ("LOCAL", "Local"),
                    ("CLOUDINARY", "Cloudinary"),
                    ("S3", "AWS S3"),
                ],
                db_index=True,
                default="AUTO",
                help_text="Where this institution's media (e.g., logo) is stored.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="institutiondocument",
            name="media_provider",
            field=models.CharField(
                choices=[
                    ("AUTO", "Auto (use Platform Config)"),
                    ("LOCAL", "Local"),
                    ("CLOUDINARY", "Cloudinary"),
                    ("S3", "AWS S3"),
                ],
                db_index=True,
                default="AUTO",
                help_text="Where this document file is stored.",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_media_provider, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="institution",
            name="logo",
            field=common.media_storage.ProviderAwareImageField(
                blank=True, null=True, upload_to="institutions/logos/"
            ),
        ),
        migrations.AlterField(
            model_name="institutiondocument",
            name="file",
            field=common.media_storage.ProviderAwareFileField(
                upload_to="institutions/documents/"
            ),
        ),
    ]
