name: Deploy Django to Oracle Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}

          script: |
            set -e

            cd /var/www/html/certrium/backend

            echo "Resetting repo..."
            git reset --hard
            git clean -fd
            git pull origin main

            echo "Activating venv..."
            source .venv/bin/activate

            echo "Upgrading pip..."
            pip install --upgrade pip

            echo "Installing requirements..."
            pip install -r requirements.txt

            echo "Running migrations..."
            python manage.py migrate --noinput

            echo "Collecting static files..."
            python manage.py collectstatic --noinput

            echo "Restarting services..."
            sudo systemctl restart certrium

            echo "Deployment successful"